"""Initial migration

Revision ID: a4de437b52ec
Revises: 
Create Date: 2026-05-30 20:49:59.972277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4de437b52ec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('availabilities_participant_id_fkey'), 'availabilities', type_='foreignkey')
    op.create_foreign_key(None, 'availabilities', 'event_participants', ['participant_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('event_participants_event_id_fkey'), 'event_participants', type_='foreignkey')
    op.drop_constraint(op.f('event_participants_user_id_fkey'), 'event_participants', type_='foreignkey')
    op.create_foreign_key(None, 'event_participants', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('magic_links_user_id_fkey'), 'magic_links', type_='foreignkey')
    op.create_foreign_key(None, 'magic_links', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('notifications_event_id_fkey'), 'notifications', type_='foreignkey')
    op.drop_constraint(op.f('notifications_user_id_fkey'), 'notifications', type_='foreignkey')
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'notifications', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('organizer_rotation_user_id_fkey'), 'organizer_rotation', type_='foreignkey')
    op.create_foreign_key(None, 'organizer_rotation', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizer_rotation', type_='foreignkey')
    op.create_foreign_key(op.f('organizer_rotation_user_id_fkey'), 'organizer_rotation', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.create_foreign_key(op.f('notifications_user_id_fkey'), 'notifications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('notifications_event_id_fkey'), 'notifications', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'magic_links', type_='foreignkey')
    op.create_foreign_key(op.f('magic_links_user_id_fkey'), 'magic_links', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'event_participants', type_='foreignkey')
    op.drop_constraint(None, 'event_participants', type_='foreignkey')
    op.create_foreign_key(op.f('event_participants_user_id_fkey'), 'event_participants', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('event_participants_event_id_fkey'), 'event_participants', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'availabilities', type_='foreignkey')
    op.create_foreign_key(op.f('availabilities_participant_id_fkey'), 'availabilities', 'event_participants', ['participant_id'], ['id'])
    # ### end Alembic commands ###
